# gen_build_version.cmake —— 编译期生成 build_version.h
#
# 用法：由 main/CMakeLists.txt 的 add_custom_target(gen_build_version) 调用
#   cmake -D BIN_DIR=<build/main> -P gen_build_version.cmake
#
# 内容：MMDDHH 格式的编译时间戳 + 项目品牌常量。每次 idf.py build 刷新。

string(TIMESTAMP _ts "%m%d%H%M" UTC)
set(_ver "0.0.1-${_ts}")

file(WRITE "${BIN_DIR}/build_version.h" [=[
/* Auto-generated by main/gen_build_version.cmake. Do not edit by hand. */
#ifndef SDG_DG_BUILD_VERSION_H
#define SDG_DG_BUILD_VERSION_H

#define BUILD_VERSION_STR  "@@VER@@"

#define SDGOODS_PROGRAM    "谷仓 SDGOODS 开放平台"
#define SDGOODS_PLATFORM   "基础工程"
#define SDGOODS_PRODUCT    "谷仓次元屏（谷仓电子徽章）"
#define SDGOODS_BRAND      "SDGOODS E-BADGE"
#define SDGOODS_VENDOR     "深圳希德创新网络有限公司 (SDGOODS)"
#define SDGOODS_HOMEPAGE   "https://github.com/SDGOODS/SDGOODS-ESP32S3"
#define SDGOODS_CONTACT_EMAIL "mailto:hello@sdgoods.example"

/* 本固件自报家门 —— 独立游戏，非官方产品 */
#define SDG_APP_NAME       "次元地牢"
#define SDG_APP_NAME_EN    "Dungeon"
#define SDG_APP_REPO       "https://github.com/YeatsLiao/sdgoods-dungeon"
#define SDG_APP_UPSTREAM   "Shattered Pixel Dungeon (c) 00-Evan"

#endif
]=])

# 替换占位符
file(READ "${BIN_DIR}/build_version.h" _content)
string(REPLACE "@@VER@@" "${_ver}" _content "${_content}")
file(WRITE "${BIN_DIR}/build_version.h" "${_content}")
